# Références applications.properties
# https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.testing
spring.profiles.active=dev,dev-database

# Chemin de l'OpenAPI
springdoc.api-docs.path=/api-docs

# Chemin de Swagger UI
springdoc.swagger-ui.path=/swagger-ui

# Trier les opérations et tags
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Afficher le temps de réponse
springdoc.swagger-ui.display-request-duration=true