# Références applications.properties
# https://docs.spring.io/spring-boot/appendix/application-properties/index.html#appendix.application-properties.testing


spring.application.name=projet4
server.port=9091



personne.id=1
personne.nom=John
personne.age=25

adresse.numero=1
adresse.rue=avenue des églantines
adresse.cp=06300
adresse.ville=Nice

spring.jpa.show-sql=true